use std::collections::BTreeMap;

/// Native property-graph paths required when the graph feature is selected.
pub const REQUIRED_GRAPH_SMOKE_COVERAGE: &[&str] = &[
    "property-graph.native-vector-index.kernel",
    "property-graph.native-vector-index.small-writes",
    "property-graph.native-vector-index.identity",
    "property-graph.native-vector-index.limit.fire",
    "property-graph.native-vector-index.control.fire",
    "property-graph.native-vector-index.reopen",
    "property-graph.native-vector-index.trace",
    "property-graph.native-vector-index.oracle.can-fire",
    "property-graph.recovery.complete-reopen",
    "property-graph.recovery.refusal",
    "property-graph.recovery.lost-ack",
    "property-graph.recovery.torn-tail",
    "property-graph.recovery.corrupt-missing-artifact",
    "property-graph.recovery.empty-history",
    "property-graph.recovery.serial-orphan",
    "property-graph.recovery.checkpoint",
    "property-graph.recovery.read-only",
    "property-graph.reclaim.physical-replacement",
    "property-graph.reclaim.stale-recheck",
    "property-graph.reclaim.inventory-fold",
    "property-graph.reclaim.protected-union",
    "property-graph.reclaim.wal-only",
    "property-graph.reclaim.capture-race",
    "property-graph.reclaim.spill-refusal",
    "property-graph.reclaim.orphan",
    "property-graph.reclaim.intent-unlink-completion",
    "property-graph.reclaim.corrupt-proof",
    "property-graph.reclaim.read-only-retirement",
    "property-graph.publication.coherent",
    "property-graph.publication.retained",
    "property-graph.publication.noop",
    "property-graph.publication.precommit",
    "property-graph.publication.uncertain",
    "property-graph.publication.result",
    "property-graph.publication.checkpoint",
    "property-graph.publication.capture",
    "property-graph.publication.creation",
    "property-graph.publication.oracle.can-fire",
    "property-graph.pattern.native-source",
    "property-graph.pattern.path-predicates",
    "property-graph.pattern.uniqueness",
    "property-graph.pattern.join-optional",
    "property-graph.pattern.full-id",
    "property-graph.pattern.retained-view",
    "property-graph.pattern.cancel.fire",
    "property-graph.pattern.limit.fire",
    "property-graph.pattern.late-error.fire",
    "property-graph.pattern.same-seed-control",
    "property-graph.pattern.release",
    "property-graph.pattern.oracle.can-fire",
    "property-graph.native-relational.pipeline",
    "property-graph.native-relational.representative",
    "property-graph.native-relational.group",
    "property-graph.native-relational.eligibility",
    "property-graph.native-relational.limit.fire",
    "property-graph.native-relational.cancel.fire",
    "property-graph.native-relational.late-error.fire",
    "property-graph.native-relational.release",
    "property-graph.native-relational.same-seed-control",
    "property-graph.native-relational.oracle.can-fire",
    "property-graph.read-view.admission-capture",
    "property-graph.read-view.old-lazy-open",
    "property-graph.read-view.coherent-reads",
    "property-graph.read-view.cursor-mismatch",
    "property-graph.read-view.source-identity-format",
    "property-graph.read-view.io.fire",
    "property-graph.read-view.io.clean",
    "property-graph.read-view.memory.fire",
    "property-graph.read-view.memory.clean",
    "property-graph.read-view.work.fire",
    "property-graph.read-view.work.clean",
    "property-graph.read-view.caller-cancel.fire",
    "property-graph.read-view.caller-cancel.clean",
    "property-graph.read-view.close-first-drain",
    "property-graph.read-view.close-drain-last-owner",
    "property-graph.read-view.close-drop-last-owner",
    "property-graph.read-view.preparation-abort",
    "property-graph.read-view.oracle.can-fire",
    "property-graph.read-view.release",
    "property-graph.directories.native-history",
    "property-graph.directories.old-root",
    "property-graph.directories.reopen",
    "property-graph.directories.range",
    "property-graph.directories.detach",
    "property-graph.directories.recreate",
    "property-graph.directories.oracle.can-fire",
    "property-graph.directories.append.fire",
    "property-graph.directories.append.clean",
    "property-graph.directories.read.fire",
    "property-graph.directories.read.clean",
    "property-graph.directories.cancel.fire",
    "property-graph.directories.cancel.clean",
    "property-graph.directories.budget.fire",
    "property-graph.directories.budget.clean",
    "property-graph.directories.private-reuse",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.aligned-owner",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.private-forged-stale",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.abort-cleanup",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.concurrent-single-owner",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.known-outcome",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.allocation.fire",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.cancel.fire",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.memory.fire",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.work.fire",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.registry.fire",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.same-seed-control",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.oracle.can-fire",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.native-map",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.native-context",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.native-final-counters",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.native-overlap",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.native-allocation.fire",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.native-cancel-work.fire",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.native-same-seed-control",
    #[cfg(feature = "graph-result-test-support")]
    "property-graph.response.native-oracle.can-fire",
    "property-graph.completed.bits-and-bags",
    "property-graph.completed.full-id",
    "property-graph.completed.oracle.can-fire",
    "property-graph.completed.copy-limit.fire",
    "property-graph.completed.cancel.fire",
    "property-graph.completed.same-seed-control",
    "property-graph.completed.release",
    "property-graph.native-result.copy",
    "property-graph.native-result.identity",
    "property-graph.native-result.same-view",
    "property-graph.native-result.limit.fire",
    "property-graph.native-result.control.fire",
    "property-graph.native-result.late-error.fire",
    "property-graph.native-result.release",
    "property-graph.native-result.oracle.can-fire",
    "property-graph.relational.order-bags",
    "property-graph.relational.collect",
    "property-graph.relational.eligible",
    "property-graph.relational.clock.sort",
    "property-graph.relational.clock.aggregate",
    "property-graph.relational.clock.eligibility",
    "property-graph.relational.same-seed-control",
    "property-graph.relational.release",
    "property-graph.adjacency.merge",
    "property-graph.adjacency.full-id",
    "property-graph.adjacency.model-paired",
    "property-graph.adjacency.oracle.can-fire",
    "property-graph.adjacency.corruption.fire",
    "property-graph.adjacency.cancel.fire",
    "property-graph.adjacency.budget.fire",
    "property-graph.adjacency.same-seed-control",
    "property-graph.adjacency-store.native-history",
    "property-graph.adjacency-store.full-id",
    "property-graph.adjacency-store.same-batch",
    "property-graph.adjacency-store.self-parallel-sparse",
    "property-graph.adjacency-store.property-only",
    "property-graph.adjacency-store.detach-raw",
    "property-graph.adjacency-store.raw-delete",
    "property-graph.adjacency-store.plain-delete-refusal",
    "property-graph.adjacency-store.old-root",
    "property-graph.adjacency-store.reopen",
    "property-graph.adjacency-store.emitted-keys",
    "property-graph.adjacency-store.participant-selection.missing-reverse",
    "property-graph.adjacency-store.participant-selection.ignored-delete",
    "property-graph.adjacency-store.append.fire",
    "property-graph.adjacency-store.append.clean",
    "property-graph.adjacency-store.budget.fire",
    "property-graph.adjacency-store.budget.clean",
    "property-graph.adjacency-store.no-partial-candidate",
    "property-graph.adjacency-store.private-release",
    // PG13 fixture comparator controls, not product I/O faults.
    "property-graph.fixture.missing-edge.fire",
    "property-graph.fixture.missing-edge.clean",
    "property-graph.fixture.narrowed-id.fire",
    "property-graph.fixture.narrowed-id.clean",
    "property-graph.fixture.resurrection.fire",
    "property-graph.fixture.resurrection.clean",
    "property-graph.fixture.multiplicity.fire",
    "property-graph.fixture.multiplicity.clean",
    "property-graph.binding.scope",
    "property-graph.binding.profile",
    "property-graph.binding.bits",
    "property-graph.binding.modes",
    "property-graph.binding.cancel.fire",
    "property-graph.binding.budget.fire",
    "property-graph.binding.same-seed-control",
    "property-graph.staging.changed",
    "property-graph.staging.replay",
    "property-graph.staging.mixed",
    "property-graph.staging.noop",
    "property-graph.staging.duplicate",
    "property-graph.staging.rejected",
    "property-graph.staging.cancel.fire",
    "property-graph.staging.cancel.clean",
    "property-graph.staging.budget.fire",
    "property-graph.staging.budget.clean",
    "property-graph.staging.oracle.can-fire",
    "property-graph.wal.prefix",
    "property-graph.wal.transition",
    "property-graph.wal.corruption.fire",
    "property-graph.wal.corruption.clean",
    "property-graph.wal.missing.fire",
    "property-graph.wal.missing.clean",
    "property-graph.wal.cancel.fire",
    "property-graph.wal.cancel.clean",
    "property-graph.wal.budget.fire",
    "property-graph.wal.budget.clean",
    "property-graph.artifact.clean",
    "property-graph.artifact.collision",
    "property-graph.artifact.entropy",
    "property-graph.artifact.before-create",
    "property-graph.artifact.after-create",
    "property-graph.artifact.torn",
    "property-graph.artifact.bit-flip",
    "property-graph.catalog.names",
    "property-graph.catalog.duplicates",
    "property-graph.catalog.high-waters",
    "property-graph.catalog.interpretation",
    "property-graph.catalog.store-identity",
    "property-graph.catalog.cancel",
    "property-graph.catalog.cancel.fire",
    "property-graph.catalog.cancel.clean",
    "property-graph.catalog.budget.fire",
    "property-graph.catalog.budget.clean",
    "property-graph.catalog.decode-error.fire",
    "property-graph.catalog.decode-error.clean",
    "property-graph.domain.zero",
    "property-graph.domain.full-width",
    "property-graph.domain.maximum",
    "property-graph.domain.random-bits",
    "property-graph.contents.order",
    "property-graph.contents.duplicate",
    "property-graph.contents.ieee-bits",
    "property-graph.contents.typed-empty",
    "property-graph.contents.full-width",
    "property-graph.contents.vector-bits",
    "property-graph.contents.forced-collision",
    "property-graph.contents.cancel",
    "property-graph.lifecycle.create",
    "property-graph.lifecycle.replay",
    "property-graph.lifecycle.conflict",
    "property-graph.lifecycle.stale",
    "property-graph.lifecycle.incarnation",
    "property-graph.lifecycle.delete",
    "property-graph.lifecycle.recreate",
    "property-graph.lifecycle.cypher",
    "property-graph.lifecycle.noop",
    "property-graph.lifecycle.overflow",
    "property-graph.lifecycle.duplicate",
    "property-graph.lifecycle.cancel",
    "property-graph.lowering.scalar-parameters",
    "property-graph.lowering.optional-pattern",
    "property-graph.lowering.hidden-order",
    "property-graph.lowering.grouping",
    "property-graph.lowering.clock.copy",
    "property-graph.lowering.clock.midpoint",
    "property-graph.lowering.clock.final-handoff",
    "property-graph.lowering.budget.fire",
    "property-graph.lowering.same-seed-control",
    "property-graph.lowering.comparator.fire",
    "property-graph.lowering.release",
    "property-graph.lowering.completed-path",
    "property-graph.search-lowering.modes",
    "property-graph.search-lowering.nullable-components",
    "property-graph.search-lowering.eligibility",
    "property-graph.search-lowering.eager-order",
    "property-graph.search-lowering.cartesian",
    "property-graph.search-lowering.invariant-backing",
    "property-graph.search-lowering.clock.fire",
    "property-graph.search-lowering.budget.fire",
    "property-graph.search-lowering.same-seed-control",
    "property-graph.search-lowering.comparator.fire",
    "property-graph.search-lowering.release",
    "property-graph.mutation-lowering.create-shapes",
    "property-graph.mutation-lowering.create-dependencies",
    "property-graph.mutation-lowering.item-order",
    "property-graph.mutation-lowering.eager-boundaries",
    "property-graph.mutation-lowering.rhs-observation",
    "property-graph.mutation-lowering.deleted-obligation",
    "property-graph.mutation-lowering.source-parameters",
    "property-graph.mutation-lowering.detach-kinds",
    "property-graph.mutation-lowering.clock.fire",
    "property-graph.mutation-lowering.budget.fire",
    "property-graph.mutation-lowering.same-seed-control",
    "property-graph.mutation-lowering.comparator.fire",
    "property-graph.mutation-lowering.owner-proof",
    "property-graph.mutation-lowering.release",
    "property-graph.query.numeric",
    "property-graph.query.grouping",
    "property-graph.query.list",
    "property-graph.query.scope",
    "property-graph.query.clock.bytes",
    "property-graph.query.clock.list",
    "property-graph.query.clock.plan",
    "property-graph.query.same-seed-control",
    "property-graph.query.pattern.scope",
    "property-graph.query.pattern.metadata",
    "property-graph.query.clock.pattern",
    "property-graph.runtime.bags",
    "property-graph.runtime.counters",
    "property-graph.runtime.clock.pull",
    "property-graph.runtime.clock.final",
    "property-graph.runtime.same-seed-control",
    "property-graph.runtime.release",
    "property-graph.query-storage.workspace",
    "property-graph.query-storage.counters",
    "property-graph.query-storage.owner-mismatch",
    "property-graph.query-storage.copy-limit.fire",
    "property-graph.query-storage.cancel.fire",
    "property-graph.query-storage.memory.fire",
    "property-graph.query-storage.same-seed-control",
    "property-graph.query-storage.oracle.can-fire",
    "property-graph.query-storage.release",
];

/// Legacy product and fault paths required by every default smoke matrix.
pub const REQUIRED_SMOKE_COVERAGE: &[&str] = &[
    "op.open",
    "op.ingest",
    "op.epoch_mismatch_probe",
    "op.prepare_epoch_b",
    "op.switch_alias_to_b",
    "op.rollback_to_a",
    "op.drop_epoch_a",
    "op.rollback_dropped_a_probe",
    "op.upsert",
    "op.revise",
    "op.delete",
    "op.drop_partition",
    "op.purge",
    "op.seal",
    "op.maintain",
    "op.search",
    "op.filtered_search",
    "op.predicate_search",
    "op.hybrid_search",
    "op.deadline_probe",
    "op.fts_extras_probe",
    "op.stats",
    "op.close",
    "op.reopen",
    "op.crash",
    "crash.boundary.mid_wal_group",
    "crash.boundary.pre_manifest_rename",
    "crash.boundary.post_manifest_rename",
    "crash.boundary.mid_seal",
    "crash.boundary.mid_purge",
    "search.scan",
    "search.auto",
    "search.graph",
    "search.filtered_graph",
    "predicate.eq",
    "predicate.in",
    "predicate.range_two_sided",
    "predicate.range_half_open",
    "predicate.bool",
    "predicate.string",
    "predicate.exists",
    "predicate.is_null",
    "predicate.and",
    "predicate.or",
    "predicate.not",
    "fts.phrase",
    "fts.prefix",
    "fts.fuzzy",
    "fts.phonetic",
    "fts.snippet",
    "store.text_ingest",
    "store.lexical_search",
    "store.hybrid_search",
    "fault.profile.none",
    "fault.profile.io-errors",
    "fault.profile.content",
    "fault.profile.crash",
    "fault.profile.disk",
    "fault.profile.clock",
    "fault.profile.full",
    "fault.profile.random",
    "fault.site.open",
    "fault.site.read",
    "fault.site.write",
    "fault.site.append",
    "fault.site.sync",
    "fault.site.rename",
    "fault.site.list",
    "fault.site.delete",
    "fault.site.clock",
    "fault.mode.eio",
    "fault.mode.eacces",
    "fault.mode.enospc",
    "fault.mode.bit_flip",
    "fault.mode.torn_write",
    "fault.mode.truncate",
    "fault.mode.wrong_object",
    "fault.mode.misdirected_write",
    "fault.mode.zero_fill",
    "fault.mode.latency",
    "fault.mode.silent_drop",
    "fault.mode.post_commit_error",
    "fault.mode.second_opener_in_process",
    "fault.mode.spawn_in_flight",
    "fault.mode.cancel",
    "fault.mode.clock_jump",
    "fault.mode.clock_stall",
    "fault.mode.crash",
];

#[cfg(feature = "graph-cypher")]
const ACTIVE_GRAPH_SMOKE_COVERAGE: &[&str] = REQUIRED_GRAPH_SMOKE_COVERAGE;
#[cfg(not(feature = "graph-cypher"))]
const ACTIVE_GRAPH_SMOKE_COVERAGE: &[&str] = &[];

pub fn required_smoke_coverage() -> impl Iterator<Item = &'static str> {
    REQUIRED_SMOKE_COVERAGE
        .iter()
        .copied()
        .chain(ACTIVE_GRAPH_SMOKE_COVERAGE.iter().copied())
}

pub const REQUIRED_LAYERED_COVERAGE: &[&str] = &[
    "fault.layer.io",
    "fault.layer.content",
    "fault.layer.crash",
    "fault.layer.clock",
    "fault.layer.cancel",
    "fault.layer.busy",
    "fault.layer.count.2",
    "fault.layer.count.3",
    "fault.layered.io+feature",
    "fault.layered.content+feature",
    "fault.layered.crash+feature",
    "fault.layered.clock+feature",
    "fault.layered.cancel+feature",
    "fault.layered.busy+feature",
    "crash.after.bit_flip",
    "crash.after.torn_write",
    "crash.after.truncate",
    "crash.after.wrong_object",
    "crash.after.misdirected_write",
    "crash.after.zero_fill",
    "crash.after.silent_drop",
];

/// A mergeable, deterministic ledger of paths that genuinely ran.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct CoverageRegistry {
    hits: BTreeMap<String, usize>,
}

impl CoverageRegistry {
    pub fn hit(&mut self, key: impl Into<String>) {
        let entry = self.hits.entry(key.into()).or_default();
        *entry = entry.saturating_add(1);
    }

    pub fn merge(&mut self, other: &Self) {
        for (key, count) in &other.hits {
            let entry = self.hits.entry(key.clone()).or_default();
            *entry = entry.saturating_add(*count);
        }
    }

    #[must_use]
    pub fn count(&self, key: &str) -> usize {
        self.hits.get(key).copied().unwrap_or(0)
    }

    #[must_use]
    pub fn missing_required_smoke(&self) -> Vec<&'static str> {
        required_smoke_coverage()
            .filter(|key| self.count(key) == 0)
            .collect()
    }

    #[must_use]
    pub fn json(&self) -> String {
        let entries = self
            .hits
            .iter()
            .map(|(key, count)| format!("\"{}\":{count}", json_escape(key)))
            .collect::<Vec<_>>()
            .join(",");
        format!("{{{entries}}}\n")
    }
}

fn json_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
