#!/usr/bin/env python3
"""Generate token-ID fixtures from pinned local source tokenizers, without models."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess

import tokenizers

PREFIX = "Represent this sentence for searching relevant passages: "
PINNED_TOKENIZERS = {
    "query": "da0e79933b9ed51798a3ae27893d3c5fa4a201126cef75586296df9b4d2c62a0",
    "document": "91f1def9b9391fdabe028cd3f3fcc4efd34e5d1f08c3bf2de513ebb5911a1854",
}
TEXTS = [
    "The bronze zeppelin.", "Café déjà vu à la carte",
    "Cafe\u0301 de\u0301ja\u0300 vu a\u0300 la carte", "İSTANBUL ΣΟΣ Straße",
    "a\u0323\u0301 o\u0308\u0304", "中文汉字 日本語 한국어",
    "Καλημέρα κόσμε Привет мир", "नमस्ते दुनिया שלום עולם",
    "alpha—beta，gamma…delta", "a\x00b\ufffdc\x01d\u200de",
    "one\t two\nthree\u00a0four\u2003five", "😀 🛰️ unknown𐀀",
    "[CLS] [MASK] [SEP]", "Å ① ﬃ ²", "a[MASK]b[SEP][PAD]c",
    "a" * 100, "a" * 101, "bronze " * 600, "",
    "ALPHA-beta_123... XYZ!", "[cls] [mask] [sep]", "a\ue000b\u0378c",
]


def rust_string(text):
    return re.sub(r"\\u([0-9a-fA-F]{4})", lambda m: "\\u{" + m[1] + "}",
                  json.dumps(text, ensure_ascii=False))


def pinned_tokenizer(root, role):
    path = root / "tokenizer.json"
    if hashlib.sha256(path.read_bytes()).hexdigest() != PINNED_TOKENIZERS[role]:
        raise ValueError(f"{role} tokenizer does not match the pinned Step 08 source")
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--query", type=Path, required=True)
    parser.add_argument("--document", type=Path, required=True)
    parser.add_argument("--json-out", type=Path, required=True)
    parser.add_argument("--rust-out", type=Path, required=True)
    args = parser.parse_args()
    if tokenizers.__version__ != "0.22.2":
        raise ValueError("fixture generator requires source tokenizers 0.22.2")
    report = {"tokenizers": tokenizers.__version__, "max_tokens": 512, "roles": {}}
    for role, root in [("query", args.query), ("document", args.document)]:
        path = pinned_tokenizer(root, role)
        tokenizer = tokenizers.Tokenizer.from_file(str(path))
        tokenizer.no_padding()
        tokenizer.enable_truncation(max_length=512)
        prefix = PREFIX if role == "query" else ""
        rows = []
        for text in TEXTS:
            encoded = tokenizer.encode(prefix + text)
            rows.append({"text": text, "ids": encoded.ids, "mask": encoded.attention_mask,
                         "normalized": tokenizer.normalizer.normalize_str(text)})
        report["roles"][role] = {"source": str(root.resolve()),
                                 "tokenizer_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                                 "prefix": prefix, "cases": rows}
    args.json_out.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    lines = ["// Generated by tools/ze-model/tokenizer-goldens.py; do not edit expected IDs.",
             "// tokenizers 0.22.2; query 4262131b32c3182bd06e67e92ae69d7bd66e0c5c; document e58a8f756156a1293d763f17e3aae643474e9b8a."]
    for role, info in report["roles"].items():
        lines.append(f"pub const {role.upper()}_CASES: &[(&str, &[i32])] = &[")
        for row in info["cases"]:
            lines.append(f"    ({rust_string(row['text'])}, &{row['ids']}),")
        lines.append("];")
    args.rust_out.write_text("\n".join(lines) + "\n")
    subprocess.run(["rustfmt", "--edition", "2024", "--config", "skip_children=true", str(args.rust_out)], check=True)


if __name__ == "__main__":
    main()
