[package]
name = "matched-query-api"
version = "0.1.0"
edition = "2024"
publish = false
[workspace]
[dependencies]
serde_json = "=1.0.151"
zeppelin-embed = { path = "../../crates/zeppelin-embed" }
zeppelin-embed-text = { path = "../../crates/zeppelin-embed-text" }
[profile.bench]
opt-level = 3
debug = true
lto = "fat"
codegen-units = 1
strip = "none"
