[package]
name = "zeppelin-embed"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
libc.workspace = true
roaring.workspace = true
xxhash-rust.workspace = true

[dev-dependencies]
proptest.workspace = true
rand.workspace = true
rand_chacha.workspace = true
tempfile.workspace = true
