"""Python bindings for the Zeppelin Embed C ABI."""

from . import _errors as _error_module
from ._errors import *
from ._ffi import ABI_VERSION
from ._library import LIBRARY_PATH
from ._store import CancelToken, Store, epoch_identity, open, open_with_epoch
from ._types import (
    AccessMode,
    CommitTier,
    ComputeUnits,
    DurabilityMode,
    EmbeddingEpoch,
    EmbeddingRuntime,
    EmbeddingTower,
    EpochAliasReport,
    EpochDropReport,
    EpochIdentity,
    FusionMethod,
    FusionReport,
    GenerationReport,
    GraphProfile,
    MaintainReport,
    MaintenanceStatus,
    MutationReport,
    Normalization,
    PartitionReport,
    PurgeReport,
    PurgeTokenReport,
    QueryHit,
    QueryMode,
    QueryResult,
    SearchHit,
    SearchResult,
    StateReport,
    StatsReport,
    StoreState,
    Tier,
)

__all__ = [  # noqa: PLE0604
    *_error_module.__all__,
    "ABI_VERSION",
    "AccessMode",
    "CancelToken",
    "CommitTier",
    "ComputeUnits",
    "DurabilityMode",
    "EmbeddingEpoch",
    "EmbeddingRuntime",
    "EmbeddingTower",
    "EpochAliasReport",
    "EpochDropReport",
    "EpochIdentity",
    "FusionMethod",
    "FusionReport",
    "GenerationReport",
    "GraphProfile",
    "LIBRARY_PATH",
    "MaintainReport",
    "MaintenanceStatus",
    "MutationReport",
    "Normalization",
    "PartitionReport",
    "PurgeReport",
    "PurgeTokenReport",
    "QueryHit",
    "QueryMode",
    "QueryResult",
    "SearchHit",
    "SearchResult",
    "StateReport",
    "StatsReport",
    "Store",
    "StoreState",
    "Tier",
    "epoch_identity",
    "open",
    "open_with_epoch",
]
