#include "zeppelin_graph_contracts.h"
#include <stdio.h>
int main(void) {
printf("ZeNodeId %zu %zu", sizeof(ZeNodeId), _Alignof(ZeNodeId));
printf(" high=%zu", offsetof(ZeNodeId, high));
printf(" low=%zu", offsetof(ZeNodeId, low));
puts("");
printf("ZeRelId %zu %zu", sizeof(ZeRelId), _Alignof(ZeRelId));
printf(" high=%zu", offsetof(ZeRelId, high));
printf(" low=%zu", offsetof(ZeRelId, low));
puts("");
printf("ZeGraphHandle %zu %zu", sizeof(ZeGraphHandle), _Alignof(ZeGraphHandle));
printf(" token=%zu", offsetof(ZeGraphHandle, token));
puts("");
printf("ZeGraphRange %zu %zu", sizeof(ZeGraphRange), _Alignof(ZeGraphRange));
printf(" start=%zu", offsetof(ZeGraphRange, start));
printf(" count=%zu", offsetof(ZeGraphRange, count));
puts("");
printf("ZeGraphValue %zu %zu", sizeof(ZeGraphValue), _Alignof(ZeGraphValue));
printf(" abi_size=%zu", offsetof(ZeGraphValue, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphValue, abi_reserved));
printf(" tag=%zu", offsetof(ZeGraphValue, tag));
printf(" list_kind=%zu", offsetof(ZeGraphValue, list_kind));
printf(" boolean=%zu", offsetof(ZeGraphValue, boolean));
printf(" entity_index=%zu", offsetof(ZeGraphValue, entity_index));
printf(" integer=%zu", offsetof(ZeGraphValue, integer));
printf(" floating=%zu", offsetof(ZeGraphValue, floating));
printf(" range=%zu", offsetof(ZeGraphValue, range));
puts("");
printf("ZeGraphBytes %zu %zu", sizeof(ZeGraphBytes), _Alignof(ZeGraphBytes));
printf(" data=%zu", offsetof(ZeGraphBytes, data));
printf(" count=%zu", offsetof(ZeGraphBytes, count));
puts("");
printf("ZeGraphControl %zu %zu", sizeof(ZeGraphControl), _Alignof(ZeGraphControl));
printf(" abi_size=%zu", offsetof(ZeGraphControl, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphControl, abi_reserved));
printf(" cancel_token=%zu", offsetof(ZeGraphControl, cancel_token));
printf(" deadline_ns=%zu", offsetof(ZeGraphControl, deadline_ns));
puts("");
printf("ZeGraphProperty %zu %zu", sizeof(ZeGraphProperty), _Alignof(ZeGraphProperty));
printf(" abi_size=%zu", offsetof(ZeGraphProperty, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphProperty, abi_reserved));
printf(" name=%zu", offsetof(ZeGraphProperty, name));
printf(" value=%zu", offsetof(ZeGraphProperty, value));
printf(" reserved=%zu", offsetof(ZeGraphProperty, reserved));
puts("");
printf("ZeGraphNode %zu %zu", sizeof(ZeGraphNode), _Alignof(ZeGraphNode));
printf(" abi_size=%zu", offsetof(ZeGraphNode, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphNode, abi_reserved));
printf(" id=%zu", offsetof(ZeGraphNode, id));
printf(" has_key=%zu", offsetof(ZeGraphNode, has_key));
printf(" has_text=%zu", offsetof(ZeGraphNode, has_text));
printf(" has_vector=%zu", offsetof(ZeGraphNode, has_vector));
printf(" reserved=%zu", offsetof(ZeGraphNode, reserved));
printf(" namespace_name=%zu", offsetof(ZeGraphNode, namespace_name));
printf(" key=%zu", offsetof(ZeGraphNode, key));
printf(" revision=%zu", offsetof(ZeGraphNode, revision));
printf(" last_change_generation=%zu", offsetof(ZeGraphNode, last_change_generation));
printf(" properties=%zu", offsetof(ZeGraphNode, properties));
printf(" text=%zu", offsetof(ZeGraphNode, text));
printf(" vector=%zu", offsetof(ZeGraphNode, vector));
printf(" labels=%zu", offsetof(ZeGraphNode, labels));
puts("");
printf("ZeGraphRelationship %zu %zu", sizeof(ZeGraphRelationship), _Alignof(ZeGraphRelationship));
printf(" abi_size=%zu", offsetof(ZeGraphRelationship, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphRelationship, abi_reserved));
printf(" id=%zu", offsetof(ZeGraphRelationship, id));
printf(" source=%zu", offsetof(ZeGraphRelationship, source));
printf(" target=%zu", offsetof(ZeGraphRelationship, target));
printf(" has_key=%zu", offsetof(ZeGraphRelationship, has_key));
printf(" reserved=%zu", offsetof(ZeGraphRelationship, reserved));
printf(" namespace_name=%zu", offsetof(ZeGraphRelationship, namespace_name));
printf(" key=%zu", offsetof(ZeGraphRelationship, key));
printf(" revision=%zu", offsetof(ZeGraphRelationship, revision));
printf(" last_change_generation=%zu", offsetof(ZeGraphRelationship, last_change_generation));
printf(" properties=%zu", offsetof(ZeGraphRelationship, properties));
printf(" relationship_type=%zu", offsetof(ZeGraphRelationship, relationship_type));
puts("");
printf("ZeGraphValuePool %zu %zu", sizeof(ZeGraphValuePool), _Alignof(ZeGraphValuePool));
printf(" abi_size=%zu", offsetof(ZeGraphValuePool, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphValuePool, abi_reserved));
printf(" values=%zu", offsetof(ZeGraphValuePool, values));
printf(" value_count=%zu", offsetof(ZeGraphValuePool, value_count));
printf(" children=%zu", offsetof(ZeGraphValuePool, children));
printf(" child_count=%zu", offsetof(ZeGraphValuePool, child_count));
printf(" bytes=%zu", offsetof(ZeGraphValuePool, bytes));
printf(" byte_count=%zu", offsetof(ZeGraphValuePool, byte_count));
printf(" nodes=%zu", offsetof(ZeGraphValuePool, nodes));
printf(" node_count=%zu", offsetof(ZeGraphValuePool, node_count));
printf(" relationships=%zu", offsetof(ZeGraphValuePool, relationships));
printf(" relationship_count=%zu", offsetof(ZeGraphValuePool, relationship_count));
printf(" properties=%zu", offsetof(ZeGraphValuePool, properties));
printf(" property_count=%zu", offsetof(ZeGraphValuePool, property_count));
printf(" names=%zu", offsetof(ZeGraphValuePool, names));
printf(" name_count=%zu", offsetof(ZeGraphValuePool, name_count));
printf(" vectors=%zu", offsetof(ZeGraphValuePool, vectors));
printf(" vector_count=%zu", offsetof(ZeGraphValuePool, vector_count));
puts("");
printf("ZeGraphEndpoint %zu %zu", sizeof(ZeGraphEndpoint), _Alignof(ZeGraphEndpoint));
printf(" abi_size=%zu", offsetof(ZeGraphEndpoint, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphEndpoint, abi_reserved));
printf(" kind=%zu", offsetof(ZeGraphEndpoint, kind));
printf(" local_item=%zu", offsetof(ZeGraphEndpoint, local_item));
printf(" node=%zu", offsetof(ZeGraphEndpoint, node));
puts("");
printf("ZeGraphBatchItem %zu %zu", sizeof(ZeGraphBatchItem), _Alignof(ZeGraphBatchItem));
printf(" abi_size=%zu", offsetof(ZeGraphBatchItem, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphBatchItem, abi_reserved));
printf(" entity_kind=%zu", offsetof(ZeGraphBatchItem, entity_kind));
printf(" operation=%zu", offsetof(ZeGraphBatchItem, operation));
printf(" namespace_name=%zu", offsetof(ZeGraphBatchItem, namespace_name));
printf(" key=%zu", offsetof(ZeGraphBatchItem, key));
printf(" revision=%zu", offsetof(ZeGraphBatchItem, revision));
printf(" expected_node=%zu", offsetof(ZeGraphBatchItem, expected_node));
printf(" expected_relationship=%zu", offsetof(ZeGraphBatchItem, expected_relationship));
printf(" expected_deletion_revision=%zu", offsetof(ZeGraphBatchItem, expected_deletion_revision));
printf(" delete_mode=%zu", offsetof(ZeGraphBatchItem, delete_mode));
printf(" has_image=%zu", offsetof(ZeGraphBatchItem, has_image));
printf(" image=%zu", offsetof(ZeGraphBatchItem, image));
printf(" reserved=%zu", offsetof(ZeGraphBatchItem, reserved));
printf(" source=%zu", offsetof(ZeGraphBatchItem, source));
printf(" target=%zu", offsetof(ZeGraphBatchItem, target));
puts("");
printf("ZeGraphBatchRequest %zu %zu", sizeof(ZeGraphBatchRequest), _Alignof(ZeGraphBatchRequest));
printf(" abi_size=%zu", offsetof(ZeGraphBatchRequest, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphBatchRequest, abi_reserved));
printf(" items=%zu", offsetof(ZeGraphBatchRequest, items));
printf(" item_count=%zu", offsetof(ZeGraphBatchRequest, item_count));
printf(" pool=%zu", offsetof(ZeGraphBatchRequest, pool));
printf(" control=%zu", offsetof(ZeGraphBatchRequest, control));
puts("");
printf("ZeGraphOptionalIndex %zu %zu", sizeof(ZeGraphOptionalIndex), _Alignof(ZeGraphOptionalIndex));
printf(" present=%zu", offsetof(ZeGraphOptionalIndex, present));
printf(" index=%zu", offsetof(ZeGraphOptionalIndex, index));
puts("");
printf("ZeGraphExpression %zu %zu", sizeof(ZeGraphExpression), _Alignof(ZeGraphExpression));
printf(" abi_size=%zu", offsetof(ZeGraphExpression, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphExpression, abi_reserved));
printf(" kind=%zu", offsetof(ZeGraphExpression, kind));
printf(" operation=%zu", offsetof(ZeGraphExpression, operation));
printf(" left=%zu", offsetof(ZeGraphExpression, left));
printf(" right=%zu", offsetof(ZeGraphExpression, right));
printf(" has_operand=%zu", offsetof(ZeGraphExpression, has_operand));
printf(" distinct=%zu", offsetof(ZeGraphExpression, distinct));
printf(" value=%zu", offsetof(ZeGraphExpression, value));
printf(" reserved=%zu", offsetof(ZeGraphExpression, reserved));
printf(" name=%zu", offsetof(ZeGraphExpression, name));
printf(" children=%zu", offsetof(ZeGraphExpression, children));
puts("");
printf("ZeGraphProjection %zu %zu", sizeof(ZeGraphProjection), _Alignof(ZeGraphProjection));
printf(" abi_size=%zu", offsetof(ZeGraphProjection, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphProjection, abi_reserved));
printf(" slot=%zu", offsetof(ZeGraphProjection, slot));
printf(" expression=%zu", offsetof(ZeGraphProjection, expression));
puts("");
printf("ZeGraphSortKey %zu %zu", sizeof(ZeGraphSortKey), _Alignof(ZeGraphSortKey));
printf(" abi_size=%zu", offsetof(ZeGraphSortKey, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphSortKey, abi_reserved));
printf(" expression=%zu", offsetof(ZeGraphSortKey, expression));
printf(" descending=%zu", offsetof(ZeGraphSortKey, descending));
puts("");
printf("ZeGraphParameter %zu %zu", sizeof(ZeGraphParameter), _Alignof(ZeGraphParameter));
printf(" abi_size=%zu", offsetof(ZeGraphParameter, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphParameter, abi_reserved));
printf(" name=%zu", offsetof(ZeGraphParameter, name));
printf(" kinds=%zu", offsetof(ZeGraphParameter, kinds));
printf(" reserved=%zu", offsetof(ZeGraphParameter, reserved));
puts("");
printf("ZeGraphParameterValue %zu %zu", sizeof(ZeGraphParameterValue), _Alignof(ZeGraphParameterValue));
printf(" abi_size=%zu", offsetof(ZeGraphParameterValue, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphParameterValue, abi_reserved));
printf(" name=%zu", offsetof(ZeGraphParameterValue, name));
printf(" value=%zu", offsetof(ZeGraphParameterValue, value));
printf(" reserved=%zu", offsetof(ZeGraphParameterValue, reserved));
puts("");
printf("ZeGraphSearchOptions %zu %zu", sizeof(ZeGraphSearchOptions), _Alignof(ZeGraphSearchOptions));
printf(" abi_size=%zu", offsetof(ZeGraphSearchOptions, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphSearchOptions, abi_reserved));
printf(" graph_profile=%zu", offsetof(ZeGraphSearchOptions, graph_profile));
printf(" graph_ef=%zu", offsetof(ZeGraphSearchOptions, graph_ef));
printf(" graph_seed=%zu", offsetof(ZeGraphSearchOptions, graph_seed));
printf(" lexical_flags=%zu", offsetof(ZeGraphSearchOptions, lexical_flags));
printf(" rescore=%zu", offsetof(ZeGraphSearchOptions, rescore));
printf(" has_alpha=%zu", offsetof(ZeGraphSearchOptions, has_alpha));
printf(" rules_enabled=%zu", offsetof(ZeGraphSearchOptions, rules_enabled));
printf(" alpha=%zu", offsetof(ZeGraphSearchOptions, alpha));
printf(" has_max_rounds=%zu", offsetof(ZeGraphSearchOptions, has_max_rounds));
printf(" reserved=%zu", offsetof(ZeGraphSearchOptions, reserved));
printf(" max_rounds=%zu", offsetof(ZeGraphSearchOptions, max_rounds));
puts("");
printf("ZeGraphSearch %zu %zu", sizeof(ZeGraphSearch), _Alignof(ZeGraphSearch));
printf(" abi_size=%zu", offsetof(ZeGraphSearch, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphSearch, abi_reserved));
printf(" kind=%zu", offsetof(ZeGraphSearch, kind));
printf(" call_id=%zu", offsetof(ZeGraphSearch, call_id));
printf(" vector=%zu", offsetof(ZeGraphSearch, vector));
printf(" text=%zu", offsetof(ZeGraphSearch, text));
printf(" k=%zu", offsetof(ZeGraphSearch, k));
printf(" has_tier=%zu", offsetof(ZeGraphSearch, has_tier));
printf(" tier=%zu", offsetof(ZeGraphSearch, tier));
printf(" reserved=%zu", offsetof(ZeGraphSearch, reserved));
printf(" eligible_set=%zu", offsetof(ZeGraphSearch, eligible_set));
printf(" window=%zu", offsetof(ZeGraphSearch, window));
printf(" node_slot=%zu", offsetof(ZeGraphSearch, node_slot));
printf(" score_slot=%zu", offsetof(ZeGraphSearch, score_slot));
printf(" vector_distance_slot=%zu", offsetof(ZeGraphSearch, vector_distance_slot));
printf(" lexical_score_slot=%zu", offsetof(ZeGraphSearch, lexical_score_slot));
printf(" options=%zu", offsetof(ZeGraphSearch, options));
puts("");
printf("ZeGraphOperator %zu %zu", sizeof(ZeGraphOperator), _Alignof(ZeGraphOperator));
printf(" abi_size=%zu", offsetof(ZeGraphOperator, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphOperator, abi_reserved));
printf(" kind=%zu", offsetof(ZeGraphOperator, kind));
printf(" entity_kind=%zu", offsetof(ZeGraphOperator, entity_kind));
printf(" inputs=%zu", offsetof(ZeGraphOperator, inputs));
printf(" predicate=%zu", offsetof(ZeGraphOperator, predicate));
printf(" source_slot=%zu", offsetof(ZeGraphOperator, source_slot));
printf(" node_slot=%zu", offsetof(ZeGraphOperator, node_slot));
printf(" relationship_slot=%zu", offsetof(ZeGraphOperator, relationship_slot));
printf(" set_slot=%zu", offsetof(ZeGraphOperator, set_slot));
printf(" direction=%zu", offsetof(ZeGraphOperator, direction));
printf(" pattern=%zu", offsetof(ZeGraphOperator, pattern));
printf(" name=%zu", offsetof(ZeGraphOperator, name));
printf(" has_name=%zu", offsetof(ZeGraphOperator, has_name));
printf(" key_expression=%zu", offsetof(ZeGraphOperator, key_expression));
printf(" node_id=%zu", offsetof(ZeGraphOperator, node_id));
printf(" relationship_id=%zu", offsetof(ZeGraphOperator, relationship_id));
printf(" relationship_types=%zu", offsetof(ZeGraphOperator, relationship_types));
printf(" path_min=%zu", offsetof(ZeGraphOperator, path_min));
printf(" path_max=%zu", offsetof(ZeGraphOperator, path_max));
printf(" edge_predicate=%zu", offsetof(ZeGraphOperator, edge_predicate));
printf(" edge_slot=%zu", offsetof(ZeGraphOperator, edge_slot));
printf(" search=%zu", offsetof(ZeGraphOperator, search));
printf(" projections=%zu", offsetof(ZeGraphOperator, projections));
printf(" aggregates=%zu", offsetof(ZeGraphOperator, aggregates));
printf(" sort_keys=%zu", offsetof(ZeGraphOperator, sort_keys));
printf(" mutations=%zu", offsetof(ZeGraphOperator, mutations));
printf(" offset=%zu", offsetof(ZeGraphOperator, offset));
printf(" limit=%zu", offsetof(ZeGraphOperator, limit));
printf(" has_limit=%zu", offsetof(ZeGraphOperator, has_limit));
printf(" reserved=%zu", offsetof(ZeGraphOperator, reserved));
puts("");
printf("ZeGraphMutation %zu %zu", sizeof(ZeGraphMutation), _Alignof(ZeGraphMutation));
printf(" abi_size=%zu", offsetof(ZeGraphMutation, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphMutation, abi_reserved));
printf(" kind=%zu", offsetof(ZeGraphMutation, kind));
printf(" output=%zu", offsetof(ZeGraphMutation, output));
printf(" entity=%zu", offsetof(ZeGraphMutation, entity));
printf(" value=%zu", offsetof(ZeGraphMutation, value));
printf(" source=%zu", offsetof(ZeGraphMutation, source));
printf(" target=%zu", offsetof(ZeGraphMutation, target));
printf(" present=%zu", offsetof(ZeGraphMutation, present));
printf(" detach=%zu", offsetof(ZeGraphMutation, detach));
printf(" name=%zu", offsetof(ZeGraphMutation, name));
printf(" labels=%zu", offsetof(ZeGraphMutation, labels));
puts("");
printf("ZeGraphPlan %zu %zu", sizeof(ZeGraphPlan), _Alignof(ZeGraphPlan));
printf(" abi_size=%zu", offsetof(ZeGraphPlan, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphPlan, abi_reserved));
printf(" root=%zu", offsetof(ZeGraphPlan, root));
printf(" reserved=%zu", offsetof(ZeGraphPlan, reserved));
printf(" operators=%zu", offsetof(ZeGraphPlan, operators));
printf(" operator_count=%zu", offsetof(ZeGraphPlan, operator_count));
printf(" expressions=%zu", offsetof(ZeGraphPlan, expressions));
printf(" expression_count=%zu", offsetof(ZeGraphPlan, expression_count));
printf(" inputs=%zu", offsetof(ZeGraphPlan, inputs));
printf(" input_count=%zu", offsetof(ZeGraphPlan, input_count));
printf(" expression_children=%zu", offsetof(ZeGraphPlan, expression_children));
printf(" expression_child_count=%zu", offsetof(ZeGraphPlan, expression_child_count));
printf(" projections=%zu", offsetof(ZeGraphPlan, projections));
printf(" projection_count=%zu", offsetof(ZeGraphPlan, projection_count));
printf(" sort_keys=%zu", offsetof(ZeGraphPlan, sort_keys));
printf(" sort_key_count=%zu", offsetof(ZeGraphPlan, sort_key_count));
printf(" mutations=%zu", offsetof(ZeGraphPlan, mutations));
printf(" mutation_count=%zu", offsetof(ZeGraphPlan, mutation_count));
printf(" parameters=%zu", offsetof(ZeGraphPlan, parameters));
printf(" parameter_count=%zu", offsetof(ZeGraphPlan, parameter_count));
printf(" searches=%zu", offsetof(ZeGraphPlan, searches));
printf(" search_count=%zu", offsetof(ZeGraphPlan, search_count));
printf(" eager_searches=%zu", offsetof(ZeGraphPlan, eager_searches));
printf(" eager_search_count=%zu", offsetof(ZeGraphPlan, eager_search_count));
printf(" pool=%zu", offsetof(ZeGraphPlan, pool));
puts("");
printf("ZeGraphQueryOptions %zu %zu", sizeof(ZeGraphQueryOptions), _Alignof(ZeGraphQueryOptions));
printf(" abi_size=%zu", offsetof(ZeGraphQueryOptions, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphQueryOptions, abi_reserved));
printf(" query_tower=%zu", offsetof(ZeGraphQueryOptions, query_tower));
printf(" alignment_digest=%zu", offsetof(ZeGraphQueryOptions, alignment_digest));
printf(" limits=%zu", offsetof(ZeGraphQueryOptions, limits));
puts("");
printf("ZeGraphQueryRequest %zu %zu", sizeof(ZeGraphQueryRequest), _Alignof(ZeGraphQueryRequest));
printf(" abi_size=%zu", offsetof(ZeGraphQueryRequest, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphQueryRequest, abi_reserved));
printf(" plan=%zu", offsetof(ZeGraphQueryRequest, plan));
printf(" parameters=%zu", offsetof(ZeGraphQueryRequest, parameters));
printf(" parameter_count=%zu", offsetof(ZeGraphQueryRequest, parameter_count));
printf(" parameter_pool=%zu", offsetof(ZeGraphQueryRequest, parameter_pool));
printf(" options=%zu", offsetof(ZeGraphQueryRequest, options));
printf(" control=%zu", offsetof(ZeGraphQueryRequest, control));
puts("");
printf("ZeGraphOpenRequest %zu %zu", sizeof(ZeGraphOpenRequest), _Alignof(ZeGraphOpenRequest));
printf(" abi_size=%zu", offsetof(ZeGraphOpenRequest, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphOpenRequest, abi_reserved));
printf(" path=%zu", offsetof(ZeGraphOpenRequest, path));
printf(" mode=%zu", offsetof(ZeGraphOpenRequest, mode));
printf(" tokenizer_profile=%zu", offsetof(ZeGraphOpenRequest, tokenizer_profile));
printf(" document_tower=%zu", offsetof(ZeGraphOpenRequest, document_tower));
printf(" reader_drain_timeout_ms=%zu", offsetof(ZeGraphOpenRequest, reader_drain_timeout_ms));
printf(" max_resident_bytes=%zu", offsetof(ZeGraphOpenRequest, max_resident_bytes));
printf(" control=%zu", offsetof(ZeGraphOpenRequest, control));
puts("");
printf("ZeGraphCypherRequest %zu %zu", sizeof(ZeGraphCypherRequest), _Alignof(ZeGraphCypherRequest));
printf(" abi_size=%zu", offsetof(ZeGraphCypherRequest, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphCypherRequest, abi_reserved));
printf(" query=%zu", offsetof(ZeGraphCypherRequest, query));
printf(" parameters=%zu", offsetof(ZeGraphCypherRequest, parameters));
printf(" parameter_count=%zu", offsetof(ZeGraphCypherRequest, parameter_count));
printf(" parameter_pool=%zu", offsetof(ZeGraphCypherRequest, parameter_pool));
printf(" options=%zu", offsetof(ZeGraphCypherRequest, options));
printf(" control=%zu", offsetof(ZeGraphCypherRequest, control));
printf(" compile_limits=%zu", offsetof(ZeGraphCypherRequest, compile_limits));
puts("");
printf("ZeGraphGetNodesRequest %zu %zu", sizeof(ZeGraphGetNodesRequest), _Alignof(ZeGraphGetNodesRequest));
printf(" abi_size=%zu", offsetof(ZeGraphGetNodesRequest, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphGetNodesRequest, abi_reserved));
printf(" ids=%zu", offsetof(ZeGraphGetNodesRequest, ids));
printf(" id_count=%zu", offsetof(ZeGraphGetNodesRequest, id_count));
printf(" include_text=%zu", offsetof(ZeGraphGetNodesRequest, include_text));
printf(" include_vector=%zu", offsetof(ZeGraphGetNodesRequest, include_vector));
printf(" control=%zu", offsetof(ZeGraphGetNodesRequest, control));
printf(" limits=%zu", offsetof(ZeGraphGetNodesRequest, limits));
puts("");
printf("ZeGraphGetRelsRequest %zu %zu", sizeof(ZeGraphGetRelsRequest), _Alignof(ZeGraphGetRelsRequest));
printf(" abi_size=%zu", offsetof(ZeGraphGetRelsRequest, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphGetRelsRequest, abi_reserved));
printf(" ids=%zu", offsetof(ZeGraphGetRelsRequest, ids));
printf(" id_count=%zu", offsetof(ZeGraphGetRelsRequest, id_count));
printf(" control=%zu", offsetof(ZeGraphGetRelsRequest, control));
printf(" limits=%zu", offsetof(ZeGraphGetRelsRequest, limits));
puts("");
printf("ZeGraphReceipt %zu %zu", sizeof(ZeGraphReceipt), _Alignof(ZeGraphReceipt));
printf(" abi_size=%zu", offsetof(ZeGraphReceipt, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphReceipt, abi_reserved));
printf(" item=%zu", offsetof(ZeGraphReceipt, item));
printf(" entity_kind=%zu", offsetof(ZeGraphReceipt, entity_kind));
printf(" disposition=%zu", offsetof(ZeGraphReceipt, disposition));
printf(" deleted=%zu", offsetof(ZeGraphReceipt, deleted));
printf(" node=%zu", offsetof(ZeGraphReceipt, node));
printf(" relationship=%zu", offsetof(ZeGraphReceipt, relationship));
printf(" revision=%zu", offsetof(ZeGraphReceipt, revision));
printf(" generation=%zu", offsetof(ZeGraphReceipt, generation));
puts("");
printf("ZeGraphColumn %zu %zu", sizeof(ZeGraphColumn), _Alignof(ZeGraphColumn));
printf(" abi_size=%zu", offsetof(ZeGraphColumn, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphColumn, abi_reserved));
printf(" name=%zu", offsetof(ZeGraphColumn, name));
printf(" kinds=%zu", offsetof(ZeGraphColumn, kinds));
printf(" reserved=%zu", offsetof(ZeGraphColumn, reserved));
puts("");
printf("ZeGraphDiagnostic %zu %zu", sizeof(ZeGraphDiagnostic), _Alignof(ZeGraphDiagnostic));
printf(" abi_size=%zu", offsetof(ZeGraphDiagnostic, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphDiagnostic, abi_reserved));
printf(" code=%zu", offsetof(ZeGraphDiagnostic, code));
printf(" reserved=%zu", offsetof(ZeGraphDiagnostic, reserved));
printf(" operator_index=%zu", offsetof(ZeGraphDiagnostic, operator_index));
printf(" has_source_span=%zu", offsetof(ZeGraphDiagnostic, has_source_span));
printf(" source_reserved=%zu", offsetof(ZeGraphDiagnostic, source_reserved));
printf(" source_span=%zu", offsetof(ZeGraphDiagnostic, source_span));
printf(" message=%zu", offsetof(ZeGraphDiagnostic, message));
puts("");
printf("ZeGraphWorkCounter %zu %zu", sizeof(ZeGraphWorkCounter), _Alignof(ZeGraphWorkCounter));
printf(" abi_size=%zu", offsetof(ZeGraphWorkCounter, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphWorkCounter, abi_reserved));
printf(" kind=%zu", offsetof(ZeGraphWorkCounter, kind));
printf(" reserved=%zu", offsetof(ZeGraphWorkCounter, reserved));
printf(" value=%zu", offsetof(ZeGraphWorkCounter, value));
puts("");
printf("ZeGraphSearchReport %zu %zu", sizeof(ZeGraphSearchReport), _Alignof(ZeGraphSearchReport));
printf(" abi_size=%zu", offsetof(ZeGraphSearchReport, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphSearchReport, abi_reserved));
printf(" call_id=%zu", offsetof(ZeGraphSearchReport, call_id));
printf(" kind=%zu", offsetof(ZeGraphSearchReport, kind));
printf(" generation=%zu", offsetof(ZeGraphSearchReport, generation));
printf(" has_requested_tier=%zu", offsetof(ZeGraphSearchReport, has_requested_tier));
printf(" requested_tier=%zu", offsetof(ZeGraphSearchReport, requested_tier));
printf(" has_actual_tier=%zu", offsetof(ZeGraphSearchReport, has_actual_tier));
printf(" actual_tier=%zu", offsetof(ZeGraphSearchReport, actual_tier));
printf(" precision=%zu", offsetof(ZeGraphSearchReport, precision));
printf(" coverage=%zu", offsetof(ZeGraphSearchReport, coverage));
printf(" vector_leg=%zu", offsetof(ZeGraphSearchReport, vector_leg));
printf(" lexical_leg=%zu", offsetof(ZeGraphSearchReport, lexical_leg));
printf(" has_document_epoch=%zu", offsetof(ZeGraphSearchReport, has_document_epoch));
printf(" has_query_epoch=%zu", offsetof(ZeGraphSearchReport, has_query_epoch));
printf(" has_tokenizer_epoch=%zu", offsetof(ZeGraphSearchReport, has_tokenizer_epoch));
printf(" cross_score_complete=%zu", offsetof(ZeGraphSearchReport, cross_score_complete));
printf(" document_epoch=%zu", offsetof(ZeGraphSearchReport, document_epoch));
printf(" query_epoch=%zu", offsetof(ZeGraphSearchReport, query_epoch));
printf(" tokenizer_epoch=%zu", offsetof(ZeGraphSearchReport, tokenizer_epoch));
printf(" effective_alpha=%zu", offsetof(ZeGraphSearchReport, effective_alpha));
printf(" normalization_version=%zu", offsetof(ZeGraphSearchReport, normalization_version));
printf(" rules_version=%zu", offsetof(ZeGraphSearchReport, rules_version));
printf(" candidate_count=%zu", offsetof(ZeGraphSearchReport, candidate_count));
printf(" cross_scored_count=%zu", offsetof(ZeGraphSearchReport, cross_scored_count));
printf(" fallback_count=%zu", offsetof(ZeGraphSearchReport, fallback_count));
printf(" work=%zu", offsetof(ZeGraphSearchReport, work));
puts("");
printf("ZeGraphResponse %zu %zu", sizeof(ZeGraphResponse), _Alignof(ZeGraphResponse));
printf(" abi_size=%zu", offsetof(ZeGraphResponse, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphResponse, abi_reserved));
printf(" owner_token=%zu", offsetof(ZeGraphResponse, owner_token));
printf(" disposition=%zu", offsetof(ZeGraphResponse, disposition));
printf(" has_admitted_generation=%zu", offsetof(ZeGraphResponse, has_admitted_generation));
printf(" admitted_generation=%zu", offsetof(ZeGraphResponse, admitted_generation));
printf(" has_changed_generation=%zu", offsetof(ZeGraphResponse, has_changed_generation));
printf(" reserved=%zu", offsetof(ZeGraphResponse, reserved));
printf(" changed_generation=%zu", offsetof(ZeGraphResponse, changed_generation));
printf(" row_count=%zu", offsetof(ZeGraphResponse, row_count));
printf(" columns=%zu", offsetof(ZeGraphResponse, columns));
printf(" column_count=%zu", offsetof(ZeGraphResponse, column_count));
printf(" cells=%zu", offsetof(ZeGraphResponse, cells));
printf(" cell_count=%zu", offsetof(ZeGraphResponse, cell_count));
printf(" pool=%zu", offsetof(ZeGraphResponse, pool));
printf(" receipts=%zu", offsetof(ZeGraphResponse, receipts));
printf(" receipt_count=%zu", offsetof(ZeGraphResponse, receipt_count));
printf(" reports=%zu", offsetof(ZeGraphResponse, reports));
printf(" report_count=%zu", offsetof(ZeGraphResponse, report_count));
printf(" diagnostics=%zu", offsetof(ZeGraphResponse, diagnostics));
printf(" diagnostic_count=%zu", offsetof(ZeGraphResponse, diagnostic_count));
printf(" work=%zu", offsetof(ZeGraphResponse, work));
printf(" work_count=%zu", offsetof(ZeGraphResponse, work_count));
printf(" global_work=%zu", offsetof(ZeGraphResponse, global_work));
puts("");
printf("ZeGraphWorkLimit %zu %zu", sizeof(ZeGraphWorkLimit), _Alignof(ZeGraphWorkLimit));
printf(" abi_size=%zu", offsetof(ZeGraphWorkLimit, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphWorkLimit, abi_reserved));
printf(" kind=%zu", offsetof(ZeGraphWorkLimit, kind));
printf(" reserved=%zu", offsetof(ZeGraphWorkLimit, reserved));
printf(" limit=%zu", offsetof(ZeGraphWorkLimit, limit));
puts("");
printf("ZeGraphQueryLimits %zu %zu", sizeof(ZeGraphQueryLimits), _Alignof(ZeGraphQueryLimits));
printf(" abi_size=%zu", offsetof(ZeGraphQueryLimits, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphQueryLimits, abi_reserved));
printf(" has_query_bytes=%zu", offsetof(ZeGraphQueryLimits, has_query_bytes));
printf(" reserved=%zu", offsetof(ZeGraphQueryLimits, reserved));
printf(" query_bytes=%zu", offsetof(ZeGraphQueryLimits, query_bytes));
printf(" work=%zu", offsetof(ZeGraphQueryLimits, work));
printf(" work_count=%zu", offsetof(ZeGraphQueryLimits, work_count));
puts("");
printf("ZeGraphCompileLimits %zu %zu", sizeof(ZeGraphCompileLimits), _Alignof(ZeGraphCompileLimits));
printf(" abi_size=%zu", offsetof(ZeGraphCompileLimits, abi_size));
printf(" abi_reserved=%zu", offsetof(ZeGraphCompileLimits, abi_reserved));
printf(" text_bytes=%zu", offsetof(ZeGraphCompileLimits, text_bytes));
printf(" tokens=%zu", offsetof(ZeGraphCompileLimits, tokens));
printf(" ast_nodes=%zu", offsetof(ZeGraphCompileLimits, ast_nodes));
printf(" depth=%zu", offsetof(ZeGraphCompileLimits, depth));
printf(" parameters=%zu", offsetof(ZeGraphCompileLimits, parameters));
printf(" columns=%zu", offsetof(ZeGraphCompileLimits, columns));
printf(" list_depth=%zu", offsetof(ZeGraphCompileLimits, list_depth));
printf(" path_hops=%zu", offsetof(ZeGraphCompileLimits, path_hops));
puts("");
return 0;
}
